export const SAFE_INPUT_PASSWORD = 'SAFE_INPUT_PASSWORD';

export const SAFE_SET_LOCK_REQUEST = 'SAFE_SET_LOCK_REQUEST';
export const SAFE_SET_LOCK_SUCCESS = 'SAFE_SET_LOCK_SUCCESS';
export const SAFE_SET_LOCK_FAIL = 'SAFE_SET_LOCK_FAIL';

export const SAFE_UNLOCK_REQUEST = 'SAFE_UNLOCK_REQUEST';
export const SAFE_UNLOCK_SUCCESS = 'SAFE_UNLOCK_SUCCESS';
export const SAFE_UNLOCK_FAIL = 'SAFE_UNLOCK_FAIL';
