export const SAFE_SET_LOCK_REQUEST = 'SAFE_SET_LOCK_REQUEST';
export const SAFE_SET_LOCK_SUCCESS = 'SAFE_SET_LOCK_SUCCESS';
export const SAFE_SET_LOCK_FAIL = 'SAFE_SET_LOCK_FAIL';
export const SAFE_SET_LOCK_RESET = 'SAFE_SET_LOCK_RESET';

export const SAFE_UNLOCK_REQUEST = 'SAFE_UNLOCK_REQUEST';
export const SAFE_UNLOCK_SUCCESS = 'SAFE_UNLOCK_SUCCESS';
export const SAFE_UNLOCK_FAIL = 'SAFE_UNLOCK_FAIL';
export const SAFE_UNLOCK_RESET = 'SAFE_UNLOCK_RESET';

export const SAFE_SERVICE_MODE_ENABLE = 'SAFE_SERVICE_MODE_ENABLE';
export const SAFE_SERVICE_MODE_DISABLE = 'SAFE_SERVICE_MODE_DISABLE';

export const SAFE_KEYPAD_LOCKED = 'SAFE_KEYPAD_LOCKED';
export const SAFE_KEYPAD_UNLOCKED = 'SAFE_KEYPAD_UNLOCKED';

export const SAFE_VALIDATE_CODE_REQUEST = 'SAFE_VALIDATE_CODE_REQUEST';
export const SAFE_VALIDATE_CODE_SUCCESS = 'SAFE_VALIDATE_CODE_SUCCESS';
export const SAFE_VALIDATE_CODE_FAIL = 'SAFE_VALIDATE_CODE_FAIL';
export const SAFE_VALIDATE_CODE_RESET = 'SAFE_VALIDATE_CODE_RESET';
